### ISSUE TITLE
Dryad sells corrupt seeds in contagion worlds

### ISSUE THREAD

**Issue by TerrorPenguin** [blahblahbal/Exxo-Avalon-Issue-Tracker#4]
During blood moons in contagion worlds the dryad should sell ickgrass seeds, but instead sells corrupt seeds

**Comment by TerrorPenguin** [comment]
This is also the case for the yellow solution from the steampunker, actually (solutions are apparently also sold during eclipses, not just blood moons)

**Comment by blahblahbal** [comment]
Fixed in 11.6.4.3.
