### ISSUE TITLE
band of slime doesn't provide +20% damage reduction

### ISSUE THREAD

**Issue by TerrorPenguin** [blahblahbal/Exxo-Avalon-Issue-Tracker#41]
the tooltip states a 20% increase, it actually provides a 10% increase (imo tooltip should be changed to 10%, but either way works)

**Comment by TerrorPenguin** [comment]
i cant believe i called it the sticky charm in baums chat AND in the bug report omg

**Comment by blahblahbal** [comment]
Fixed in 11.7 (all of these items now reduce damage taken by 10% instead of 20%).
